### ISSUE TITLE
Can't import types

### ISSUE THREAD

**Issue by burtek** [Shinigami92/eslint-define-config#207] opened 2023-06-30 12:41 UTC
After #204 was merged and released in 1.21.0, I can't do any type imports, i.e:

```ts
import type { FlatESLintConfigItem } from 'eslint-define-config';
```

![image](https://github.com/Shinigami92/eslint-define-config/assets/2940958/adea959f-aff6-48b3-b203-3ea445eb799e)
![image1](https://github.com/Shinigami92/eslint-define-config/assets/2940958/f00c392c-4bae-4b61-b917-e1e88a587d9a)

Works correctly for 1.20.0

**Comment by Shinigami92** [comment] 2023-07-01 08:18
You can push this forward by forking and try to create a bugfix PR
Otherwise you need to wait some days until I'm back in "working-mode"
I'm currently enjoying the last days of my vacation and grind Diablo 4 😅

**Comment by burtek** [comment] 2023-07-01 09:57
@Shinigami92 happy to take a look tomorrow evening once I'm back from in-laws 😅

**Comment by Shinigami92** [comment] 2023-07-03 07:22
I now had the first time after vacation to test your issue and somehow I cannot reproduce your problem 🤔

**Comment by burtek** [comment] 2023-07-03 10:01
@Shinigami92 what TS version were you testing this on?

Tried playing with it (both changing TS version, my configuration and your package.json) and can't figure out what's wrong with it...

**Comment by burtek** [comment] 2023-07-03 10:20
> When a file is considered an ES module, a few different rules come into play compared to CommonJS:
> - relative import paths need full extensions (e.g we have to write import "./foo.js" instead of import "./foo")

https://www.typescriptlang.org/docs/handbook/esm-node.html#type-in-packagejson-and-new-extensions

It started working correctly for me when I changed your .d.ts files to contain extensions. I think that's the issue here. But still interested of your setup, since you're saying it works for you as is?

**Comment by Shinigami92** [comment] 2023-07-04 05:08
I have just a normal TypeScript esm project 

I'm sorry I have not the time to debug your problems if you cannot provide a minimal reproducible

Also it starts to sound like it's a problem with your tsconfig or whatever 

So I think I will close this issue for now
Feel free to reopen when you provide a minimal reproducible

**Closed** 2023-07-04 05:09 UTC

**Comment by burtek** [comment] 2023-08-17 09:38
FFR the issue is that my project was set to have module resolution "Node16" while `eslint-define-config` is "Node" (a.k.a. "Node10") and those two don't play well.
